### PR TITLE
allow sending list of repository

### PR DESCRIPTION
**Pull request by CBaptiste**
Hello @redox 

adding a command to be able to send a list of repository.
AND removing `inquirer-checkbox-plus-prompt` 😬 not super useful if you're ok with that.

let me know what you think!

### CODE REVIEW

**Comment by CBaptiste** [comment]
What do you mean "--without-repositories " @redox ? I don't understand the "without" since we are giving a list of repo

**Comment by redox** [comment]
> What do you mean "--without-repositories " @redox ? I don't understand the "without" since we are giving a list of repo

Ah shit, I thought this option was to remove some repositories from the list. Then I would recommend using `--repositories` to override the automatic listing.

**Comment by CBaptiste** [comment]
hello @redox I fixed your comments (you already had a `config.repositories` so I created `config.repositoriesInput`
once it gets merged - let's delete and archive a first batch of **207** repositories 💥

**Comment by redox** [comment]
Cool :)

**Pull request merged**
